x-uffizzi:
  ingress:
    service: app
    port: 3000

services:
  app:
    build:
      context: https://github.com/greybutton/uffizzi-test
      dockerfile: Dockerfile
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rails s -b '0.0.0.0' -p 3000"
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 500M
