x-uffizzi:
  ingress:
    service: app
    port: 3000

services:
  app:
    build:
      context: https://github.com/greybutton/uffizzi-test
      dockerfile: Dockerfile
    environment:
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
    deploy:
      resources:
        limits:
          memory: 250M

  db:
    image: postgres:11.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
