version: '2'

services:
  db:
    image: postgres:10.3-alpine
  redis:
    image: redis:5.0.9-alpine
  ci:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ".:/app:cached"
    environment:
      - REDIS_URL=redis://redis
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - CI=true
      - DEFAULT_HOST=test.host.com
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"
