x-uffizzi:
  ingress:
    service: app
    port: 3000

services:
  app:
    build:
      context: https://github.com/greybutton/uffizzi-test
      dockerfile: Dockerfile
    command: bundle exec rails db:create db:migrate
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    deploy:
      resources:
        limits:
          memory: 500M
